[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
password = "postgres"

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

# WASTEX Project Configuration
project_id = "ibxnycomuwbloqaninji"
